#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import zipfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "dist" / "clawhub"
PACKAGE_DIR_NAME = "agentbox-skills"

INCLUDED_FILES = [
    "openclaw.plugin.json",
    "package.json",
    "package-lock.json",
    "index.js",
    "bridge.js",
    "runtime/clients.js",
    "runtime/common.js",
    "runtime/contracts.js",
    "runtime/operations.js",
    "runtime/player-runtime.js",
    "runtime/settings.js",
    "openclaw_skill/agentbox-skills/SKILL.md",
    "docs/AGENTBOX_ID_SEMANTICS.md",
    "docs/OPENCLAW_PLANNER_PROMPT.md",
    "docs/OPENCLAW_EXECUTOR_PROMPT.md",
    "agentbox_core/deployments.json",
    "agentbox_core/abi/AgentboxConfig.json",
    "agentbox_core/abi/AgentboxEconomy.json",
    "agentbox_core/abi/AgentboxLand.json",
    "agentbox_core/abi/AgentboxRandomizer.json",
    "agentbox_core/abi/AgentboxResource.json",
    "agentbox_core/abi/AgentboxRole.json",
    "agentbox_core/abi/AgentboxRoleWallet.json",
    "agentbox_core/abi/IAgentboxCore.json",
]

CHECK_JS_FILES = [path for path in INCLUDED_FILES if path.endswith(".js")]

FORBIDDEN_TEXT_PATTERNS = [
    "child_process",
    "spawn(",
    "execFile(",
    "exec(",
]

PACKAGE_README = """# Agentbox Skills

OpenClaw plugin for Agentbox gameplay automation on Base mainnet.

This ClawHub package includes:

- Agentbox gameplay tools for state reads, prerequisite checks, and onchain actions
- Operation Manager tools for long-running background gameplay state
- A local bridge used by the Agentbox web app for account, chat, active-role, operation, and background controls
- OpenClaw skill guidance for semantic user-facing responses

## Included Skill

- `./openclaw_skill/agentbox-skills`

## Included Docs

- `docs/AGENTBOX_ID_SEMANTICS.md`
- `docs/OPENCLAW_PLANNER_PROMPT.md`
- `docs/OPENCLAW_EXECUTOR_PROMPT.md`

## Configuration

The plugin exposes a `bridge` config object:

- `enabled`: enable or disable the local bridge
- `token`: bridge authentication token
- `allowedOrigins`: browser origins allowed to call the bridge
- `defaultSessionKey`: fixed Agentbox chat session key
- `sseHeartbeatMs`: SSE heartbeat interval

## Runtime Data

OpenClaw runtime data is stored under the plugin's Agentbox data directory, including local signer state, active role, owned roles, and operation state.

"""


def remove_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def copy_file(relative_path: str, package_dir: Path) -> None:
    source = REPO_ROOT / relative_path
    if not source.exists():
        raise FileNotFoundError(f"Missing required file: {source}")
    target = package_dir / relative_path
    target.parent.mkdir(parents=True, exist_ok=True)
    if relative_path == "package.json":
        payload = json.loads(source.read_text())
        payload.pop("private", None)
        target.write_text(json.dumps(payload, indent=2) + "\n")
        return
    if relative_path.startswith("agentbox_core/abi/"):
        payload = json.loads(source.read_text())
        abi = payload if isinstance(payload, list) else payload.get("abi")
        if not isinstance(abi, list):
            raise ValueError(f"ABI artifact does not contain an abi array: {source}")
        target.write_text(json.dumps(abi, separators=(",", ":")) + "\n")
        return
    shutil.copy2(source, target)


def write_package_readme(package_dir: Path) -> None:
    (package_dir / "README.md").write_text(PACKAGE_README, encoding="utf8")


def write_publish_manifest(package_dir: Path) -> None:
    plugin_json = json.loads((package_dir / "openclaw.plugin.json").read_text())
    manifest = {
        "package": plugin_json.get("id", PACKAGE_DIR_NAME),
        "name": plugin_json.get("name", "Agentbox Skills"),
        "version": plugin_json.get("version", "0.0.0"),
        "family": "code-plugin",
        "source": "generated by scripts/build_clawhub_package.py",
        "included": ["README.md", *INCLUDED_FILES],
    }
    (package_dir / "clawhub-package.json").write_text(json.dumps(manifest, indent=2) + "\n")


def scan_for_forbidden_text(package_dir: Path) -> list[str]:
    findings: list[str] = []
    for path in package_dir.rglob("*"):
        if not path.is_file() or path.suffix not in {".js", ".mjs", ".cjs"}:
            continue
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        for pattern in FORBIDDEN_TEXT_PATTERNS:
            if pattern in text:
                findings.append(f"{path.relative_to(package_dir)} contains {pattern!r}")
    return findings


def run_node_checks(package_dir: Path) -> None:
    for relative_path in CHECK_JS_FILES:
        target = package_dir / relative_path
        if target.exists():
            subprocess.run(["node", "--check", str(target)], check=True)


def build_zip(package_dir: Path) -> Path:
    archive_path = package_dir.parent / f"{package_dir.name}.zip"
    if archive_path.exists():
        archive_path.unlink()
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(package_dir.rglob("*")):
            if path.is_dir():
                continue
            archive.write(path, path.relative_to(package_dir.parent))
    return archive_path


def build_package(output_root: Path, skip_checks: bool) -> Path:
    package_dir = output_root / PACKAGE_DIR_NAME
    if package_dir.exists():
        remove_path(package_dir)
    package_dir.mkdir(parents=True, exist_ok=True)

    for relative_path in INCLUDED_FILES:
        copy_file(relative_path, package_dir)
    write_package_readme(package_dir)
    write_publish_manifest(package_dir)

    forbidden_text = scan_for_forbidden_text(package_dir)
    if forbidden_text:
        raise RuntimeError("Forbidden code patterns were found in the package:\n" + "\n".join(forbidden_text))

    if not skip_checks:
        run_node_checks(package_dir)

    return package_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a clean OpenClaw-only package for ClawHub publishing.")
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help=f"Directory that will contain the generated {PACKAGE_DIR_NAME} package.",
    )
    parser.add_argument(
        "--skip-checks",
        action="store_true",
        help="Skip node --check validation.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    package_dir = build_package(args.output_root.resolve(), args.skip_checks)
    archive_path = build_zip(package_dir)
    print(f"Built ClawHub staging directory: {package_dir}")
    print(f"Built upload archive: {archive_path}")
    print()
    print("Upload this zip at:")
    print("  https://clawhub.ai/publish-plugin")


if __name__ == "__main__":
    main()
